#!bin/sh

if [ -d "/etc/.h-tool" ]; then
	echo "Warning : /etc/.h-tool directory exist!"
	rm -rf /etc/.h-tool
fi

if [ -e "/etc/rc.local.backup" ]; then
	echo "Warning : /etc/rc.local.backup exist !"
	rm -rf /etc/rc.local.backup
fi
